### ISSUE TITLE
commas in the contents

### ISSUE THREAD

**Issue by mwilkes-lark** [1Password/solutions#21] opened 2023-01-13 16:11 UTC
as the lastpass export is comma delimited, the scripts have trouble when there are commas in the content. This is most likely occuring in the 'extra' field of the export. Programs like Google Sheets and MS Excel seem to be handling the issue a bit more gracefully by recognizing that there is a linefeed character at the end of the row of data (^M) which helps them parse the file cleanly and "walk it back" from right to left and from left to right. So the first three commas in the line should be clean for the url, username and password fields. And the last three commas should be clean for fav, grouping and name fields. But it's the 'extra' field that can contain commas if someone makes a secret note that has, for example, a mailing address for a credit card which usually contains a comma between city and state. They might also have written some explanatory text about the secret which contains commas. Plenty of other secrets in my experience contain commas as well. A tab-delimited export from lastpass would be preferred since it's unusual for someone to paste tabbed content into a secret (though it might happen of course).

So you should count the commas between start of line (^) and end of line ($), looking for the linefeed ^M as the last character and see if you can cleanly import all secrets exported without users having to do weird workarounds to accomplish the import.

**Comment by scottisloud** [comment] 2023-01-13 16:18
Thanks for this bug report and your detailed suggestions @mwilkes-lark. In our testing we did not encounter this but we have a somewhat limited set of test data compared to the users at large, so I appreciate you bringing this to the table. 

We'll take a look at how we can handle this better.

**Comment by scottisloud** [comment] 2023-01-13 23:38
@mwilkes-lark while reviewing #23 I attempted to reproduce the issue, currently hypothesized to be cause by a non-delimiting comma such as might appear in the `extra` column. 

I was unable to reproduce that issue using the current version of the script merged this afternoon. In order to reproduce, I inserted several non-delimiting commas in the `extra` field of a login item and ran the importer. The entire .csv was imported without error, including the item with the non-delimiting comma, which was imported including the comma. 

Perhaps a mere non-delimiting comma alone is not sufficient. I will continue to try to reproduce this issue as time permits. Please let me know if you are able to reproduce the issue with the latest version of the script. If you are able to reproduce it, any repro steps you can provide are appreciated. 

Thanks for documenting your issue and I am hopeful that we can nail down the cause and introduce a fix!

**Comment by mwilkes-lark** [comment] 2023-01-14 04:52
I pulled down copies of the two python scripts and ran them against this attached export.csv.gz (want to try to preserve the file that I crafted). Both scripts exit without doing anything now.

[export.csv.gz](https://github.com/1Password/solutions/files/10416585/export.csv.gz)

MacBook-Pro:1password mwilkes$ md5 folder_migrate.py 
MD5 (folder_migrate.py) = d9e8686f81fc0e24abd54c710aea3d16
MacBook-Pro:1password mwilkes$ md5 vault_item_import.py 
MD5 (vault_item_import.py) = 2e5aa49ddc75a3c622f840253d462cf0
MacBook-Pro:1password mwilkes$ date
Fri Jan 13 23:52:19 EST 2023

**Comment by mwilkes-lark** [comment] 2023-01-14 05:08
You can also try this kind of example export.csv as well that has an address:

[export.csv.gz](https://github.com/1Password/solutions/files/10416710/export.csv.gz)


MacBook-Pro:1password mwilkes$ python3 folder_migrate.py 
MacBook-Pro:1password mwilkes$ python3 vault_item_import.py 
MacBook-Pro:1password mwilkes$ wc export.csv
       6      19     247 export.csv

**Comment by scottisloud** [comment] 2023-01-16 20:30
@mwilkes-lark The sample item you provided is a secure note (as per the `http://sn` website field. This script ignores secure notes because we have not yet devised a way to reliably parse the contents of the `extra` field to make the appropriate 1Password items. 
Our web importer does handle secure notes and creates appropriate 1Password items (e.g., Credit Card, Membership, etc) where possible. 

I changed the URL of the item to see how the script handles complex content in `extra` including special or delimiting characters and the script had no issues. You can see the results of your sample item when the website if changed to a real website instead of LastPass's secure note `http://sn` value:
<img width="540" alt="CleanShot 2023-01-16 at 12 22 19@2x" src="https://user-images.githubusercontent.com/6445407/212760363-8f0be7a8-ec93-442e-986a-730230009d60.png">

Since the core of this issue is problems handling special characters in `extra`, it seems like we've resolved that specific issue, so I will be closing this issue. If you notice other bugs with login items, please feel free to open another issue. Parsing secure notes using this script is also on our radar but is not immediately planned because of the availability of other options for that purpose. 

In the meantime, for importing your secure notes, we suggest our [LastPass importer at 1Password.com](https://support.1password.com/import-lastpass/). Our developers are also working major enhancements to the LastPass experience built natively into 1Password.

**Closed by scottisloud** 2023-01-16 20:30 UTC
Labels: bug
